# Generated by Django 3.2.25 on 2024-12-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20241211_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmation',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mood'),
        ),
        migrations.AlterField(
            model_name='journalingprompt',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mood'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mood'),
        ),
        migrations.AddField(
            model_name='affirmation',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mood'),
        ),
    ]
    
