# Generated by Django 3.2.25 on 2024-12-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_mood_affirmation_mood_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affirmation',
            old_name='mood_id',
            new_name='mood',
        ),
    ]
