# Generated by Django 3.2.25 on 2024-12-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_goal_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
    ]
