# Generated by Django 3.2.25 on 2024-12-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_goal_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
